# docker/Dockerfile.simulator

# Start from the base image we created earlier
FROM python:3.12-slim

# Set working directory
WORKDIR /CI-CD-Speed-Simulator

# Copy the whole project into container
COPY . .

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Default entrypoint → run the simulator
CMD ["python3", "-m","simulator.build_simulator"]
