# ci/gitlab-ci.yml
stages:
  - test

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

test-job:
  stage: test
  image: python:3.12
  script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pytest tests/ --maxfail=1 --disable-warnings -q
